### ISSUE TITLE
AttributeError: module 'adaflow.env_runner' has no attribute 'libero_image_runner'  

### ISSUE THREAD

**Issue by deng-cy20** [hxixixh/AdaFlow#2]
Hi thanks for sharing the code. When I try to run the experiment of diffusion policy part, following error occurs:
AttributeError: module 'adaflow.env_runner' has no attribute 'libero_image_runner'  
I think env folder in 'AdaFlow/adaflow/' is missing in the repository and thus causes the problem.

**Comment by deng-cy20** [comment]
![image](https://github.com/user-attachments/assets/1845d70f-b466-407c-a29a-29349f76fcec)
![image](https://github.com/user-attachments/assets/acbd2c57-6482-48fc-a437-3878cb1f0b7b)

**Comment by hxixixh** [comment]
Hi @deng-cy20 , thanks for letting me know. I have updated the repo to include this file. Let me know if you have any other issue when running the code.
